namespace JipperOverlayer.Overlayer.Localization;

public static class Tr
{
    public enum Key
    {
        Size, ShowProgress, ShowAccuracy, ShowXAccuracy,
        ShowMusicTime, ShowMapTime, ShowMapIfNo,
        TimeTextType, TimeTextKorean, TimeTextEnglish,
        ShowCheckpoint, ShowBest,
        ShowProgressBar, ShowCombo, EnableAutoCombo, ComboColorMax,
        ShowBpm, BpmColorMax, ShowJudgement, JudgementUp, ShowXPerfectInJudgement, ShowAutoInXPerfect,
        ShowTimingScale, ShowTimingWindow, ShowAttempt, ShowFullAttempt,
        JongyeolMode, ShowFps, ShowAuthor, ShowState,
        ShowDeath, ShowStart, ShowTiming,
        HideDebugText, RemoveAutoReq, CheckPseudo, AllowELCombo, AllowOrangeCombo,
        LangLabel,
        Font, CustomPositions, ResetPositions,
        TextSettings, AlignMain, AlignBpm, AlignJudge, AlignCombo, AlignComboVal, AlignTiming, AlignAttempt, ApplyAlignment, AlignReset,
        StyleBold, StyleItalic, StyleUnderline, StyleStrike, StyleHighlight,
        ProgressColor, AccuracyColor, XaccuracyColor,
        MusicTimeColor, MapTimeColor, BestColor,
        ProgressBarColor, ProgressBarBgColor, ProgressBarBorderColor,
        ComboColor, BpmColor, AddColorStop, Delete, Percent,
        CustomLabels,
        General, Display, ProgressAccuracy, TimeSection,
        ProgressBarBest, ComboSection, BpmSection, JudgementOther,
        DisplayOptions, BehaviorOptions,
        FPSRefreshRate, DecimalPrecision,
        Coop,
        PosMain, PosBPM, PosJudge,
        PosP1, PosP2, PosP3, PosP4,
        PosCombo, PosTiming, PosAttempt, PosProgBar,
        FpsColor, AuthorColor, StateDefaultColor, StateAutoTileColor, StateAutoColor, StatePerfectColor,
        StateCompleteColor, StateClearColor, StateNoMissColor, StatePerfectionistColor,
        DeathColor, StartColor, TimingColor, JComboColor,
        DisplayOrder, ResetOrder,
        ElemProgress, ElemAccuracy, ElemXAccuracy, ElemMusicTime, ElemMapTime,
        ElemCheckpoint, ElemBest, ElemBPM, ElemAttempt, ElemTimingScale,
        ElemFPS, ElemAuthor, ElemState, ElemDeath, ElemStart, ElemTiming,
        BpmLineTile, BpmLineCur, BpmLineKps,
        AttemptLineAttempt, AttemptLineFull,
        ComboLineReversed,
        PatchBetaWatermark, PatchLevelName, RepositionAutoText,
        TextEffects, TextEffectShadow, TextEffectShadowColor, TextEffectShadowSoftness,
        TextEffectShadowOffsetX, TextEffectShadowOffsetY,
        TextEffectOutline, TextEffectOutlineColor, TextEffectOutlineWidth, TextEffectOutlineSoftness,
        DetailedProgress, TimeDecimals,
        ShowXScore, XScoreColor, TextType,
        ElemAvgTiming, ElemXScore, ElemPAcc, ElemPXAcc, ElemPXScore,
        Count
    }

    private static readonly string[][] Data =
    [
        /* 0  English */ [ "Size", "Show Progress", "Show Accuracy", "Show XAccuracy",
            "Show Music Time", "Show Map Time", "Show Map Time If No Music",
            "Time Text Type", "Korean", "English",
            "Show Checkpoint", "Show Best",
            "Show Progress Bar", "Show Combo", "Enable Auto Combo", "Combo Color Max",
            "Show BPM", "BPM Color Max", "Show Judgement", "Judgement Location Up","Show XPerfect In Judgement",
            "Show Auto In XPerfect",
            "Show Timing Scale", "Show Timing Window", "Show Attempt", "Show Full Attempt",
            "Jongyeol Mode", "Show FPS", "Show Author", "Show State",
            "Show Death", "Show Start", "Show Timing",
            "Hide Debug Text", "Remove Not Required In Auto", "Check Pseudo", "EL Judgment Combo", "VL Judgment Combo",
            "Language",
            "Font", "Custom Positions", "Reset Positions",
            "Text Settings", "Main", "BPM", "Judge", "Combo Title", "Combo Value", "Timing Scale", "Attempt", "Apply Alignment", "Reset",
            "B", "I", "U", "S", "H",
            "Progress Color", "Accuracy Color", "XAccuracy Color",
            "Music Time Color", "Map Time Color", "Best Color",
            "Progress Bar Color", "Progress Bar Background Color", "Progress Bar Border Color",
            "Combo Color", "BPM Color", "Add Color Stop", "Delete", "Percent", "Custom Labels",
            "General", "Display", "Progress && Accuracy", "Time",
            "Progress Bar && Best", "Combo", "BPM", "Judgement && Other",
            "Display Options", "Behavior Options", "FPS Refresh Rate", "Decimal Precision",
            "Coop",
            "Main", "BPM", "Judge", "P1", "P2", "P3", "P4", "Combo", "Timing", "Attempt", "ProgBar",
            "FPS Color", "Author Color", "State Default Color", "State Auto-tile Color", "State Auto Color", "State Perfect Color",
            "State Complete Color", "State Clear Color", "State No Miss Color", "State Perfectionist Color",
            "Death Color", "Start Color", "Timing Color", "Combo Color",
            "Display Order", "Reset Order",
            "Progress", "Accuracy", "XAccuracy", "Music Time", "Map Time",
            "Checkpoint", "Best", "BPM", "Attempt", "Timing Scale",
            "FPS", "Author", "State", "Death", "Start", "Timing",
            "Tile BPM", "Cur BPM", "KPS",
            "Attempt", "Full Attempt", "Reverse Combo Order",
            "Patch Beta Watermark", "Patch Level Name", "Reposition Auto Text",
            "Text Effects", "Shadow", "Shadow Color", "Shadow Softness",
            "Shadow Offset X", "Shadow Offset Y",
            "Outline", "Outline Color", "Outline Width", "Outline Softness",
            "Detailed Progress (cur / total)", "Time With Decimals",
            "Show XScore", "XScore Color", "Text Type",
            "Avg Timing", "XScore", "P.Accuracy", "P.XAccuracy", "P.XScore" ],

        /* 1  Korean */ [ "크기", "진행도 표시", "정확도 표시", "X정확도 표시",
            "음악 시간 표시", "맵 시간 표시", "음악 없을 때 맵 시간",
            "시간 텍스트 타입", "한국어", "영어",
            "체크포인트 표시", "최고 기록 표시",
            "진행 바 표시", "콤보 표시", "자동 콤보 활성화", "콤보 색상 최대",
            "BPM 표시", "BPM 색상 최대", "판정 표시", "판정 위치 위로","XPerfect 표시",
            "XPerfect 자동 타일 표시",
            "타이밍 스케일 표시", "판정 시간 창 표시", "시도 횟수 표시", "전체 시도 표시",
            "종열 모드", "FPS 표시", "제작자 표시", "상태 표시",
            "사망 표시", "시작 표시", "타이밍 표시",
            "디버그 텍스트 숨기기", "자동에서 불필요한 것 제거", "의사 BPM 확인", "EL 판정 콤보", "VL 판정 콤보",
            "언어",
            "글꼴", "사용자 지정 위치", "위치 초기화",
            "텍스트 설정", "메인", "BPM", "판정", "콤보 제목", "콤보 값", "타이밍 스케일", "시도", "정렬 적용", "초기화",
            "B", "I", "U", "S", "H",
            "진행도 색상", "정확도 색상", "X정확도 색상",
            "음악 시간 색상", "맵 시간 색상", "최고 기록 색상",
            "진행 바 색상", "진행 바 배경 색상", "진행 바 테두리 색상",
            "콤보 색상", "BPM 색상", "색상 포인트 추가", "삭제", "퍼센트", "사용자 레이블",
            "일반", "디스플레이", "진행 및 정확도", "시간",
            "진행 바 및 최고 기록", "콤보", "BPM", "판정 및 기타",
            "표시 옵션", "동작 옵션", "FPS 새로고침 속도", "소수점 자릿수",
            "협동",
            "메인", "BPM", "판정", "P1", "P2", "P3", "P4", "콤보", "타이밍", "시도", "프로그레스바",
            "FPS 색상", "제작자 색상", "상태 기본 색상", "상태 자동 타일 색상", "상태 자동 색상", "상태 퍼펙트 색상",
            "상태 완주 색상", "상태 클리어 색상", "상태 노미스 색상", "상태 완벽주의 색상",
            "사망 색상", "시작 색상", "타이밍 색상", "콤보 색상",
            "표시 순서", "순서 초기화",
            "진행도", "정확도", "X정확도", "음악 시간", "맵 시간",
            "체크포인트", "최고 기록", "BPM", "시도", "타이밍 스케일",
            "FPS", "제작자", "상태", "사망", "시작", "타이밍",
            "타일 BPM", "현재 BPM", "KPS",
            "시도 횟수", "전체 시도", "콤보 순서 반전",
            "베타 워터마크 패치", "레벨 이름 패치", "오토 텍스트 재배치",
            "텍스트 효과", "그림자", "그림자 색상", "그림자 부드러움",
            "그림자 오프셋 X", "그림자 오프셋 Y",
            "아웃라인", "아웃라인 색상", "아웃라인 두께", "아웃라인 부드러움",
            "상세 진행도 (현재 / 전체)", "시간 소수점 표시",
            "XScore 표시", "XScore 색상", "텍스트 타입",
            "평균 타이밍", "XScore", "P.정확도", "P.X정확도", "P.XScore" ],

        /* 2  Chinese */ [ "大小", "显示进度", "显示准确率", "显示X准确率",
            "显示音乐时间", "显示地图时间", "无音乐时显示地图时间",
            "时间文本类型", "韩文", "英文",
            "显示检查点", "显示最佳",
            "显示进度条", "显示连击", "启用自动方块连击", "连击颜色最大值",
            "显示BPM", "BPM颜色最大值", "显示判定", "判定位置上移","显示XPerfect",
            "XPerfect模式显示自动方块",
            "显示判定区间", "显示判定时间窗", "显示尝试次数", "显示总尝试次数",
            "Jongyeol模式", "显示FPS", "显示作者", "显示状态",
            "显示死亡", "显示开始", "显示时机",
            "隐藏调试文本", "自动模式简化显示", "检测伪BPM", "允许EL判定连击", "允许VL判定连击",
            "语言",
            "字体", "自定义位置", "重置位置",
            "文本设置", "主区域", "BPM", "判定", "连击标题", "连击数值", "判定区间", "尝试", "应用对齐", "重置",
            "B", "I", "U", "S", "H",
            "进度颜色", "准确率颜色", "X准确率颜色",
            "音乐时间颜色", "地图时间颜色", "最佳颜色",
            "进度条颜色", "进度条背景颜色", "进度条边框颜色",
            "连击颜色", "BPM颜色", "添加颜色点", "删除", "百分比", "自定义标签",
            "通用", "显示", "进度与准确率", "时间",
            "进度条与最佳", "连击", "BPM", "判定与其他",
            "显示选项", "行为选项", "FPS刷新率", "小数位数",
            "合作",
            "主区域", "BPM", "判定", "P1", "P2", "P3", "P4", "连击", "判定区间", "尝试", "进度条",
            "FPS颜色", "作者颜色", "状态默认颜色", "状态自动方块颜色", "状态自动颜色", "状态完美颜色",
            "状态完成颜色", "状态通关颜色", "状态无Miss颜色", "状态完美主义颜色",
            "死亡颜色", "开始颜色", "时机颜色", "连击颜色",
            "显示顺序", "重置顺序",
            "进度", "准确率", "X准确率", "音乐时间", "地图时间",
            "检查点", "最佳", "BPM", "尝试", "判定区间",
            "FPS", "作者", "状态", "死亡", "开始", "时机",
            "Tile BPM", "当前 BPM", "KPS",
            "尝试", "总尝试", "反转连击顺序",
            "Beta水印调整", "关卡名调整", "自动播放文本重定位",
            "文本特效", "阴影", "阴影颜色", "阴影柔和度",
            "阴影偏移 X", "阴影偏移 Y",
            "描边", "描边颜色", "描边宽度", "描边柔和度",
            "详细进度（当前 / 总数）", "时间显示小数",
            "显示XScore", "XScore颜色", "文本类型",
            "平均时机", "XScore", "P.准确率", "P.X准确率", "P.XScore" ],
    ];

    public static string Get(Key key)
    {
        if (Main.Settings == null) return Data[0][(int)key];
        return Data[(int)Main.Settings.CurrentLanguage][(int)key];
    }

    /// <summary>Union of every character used by any language's UI strings (for glyph pre-baking).</summary>
    public static string CollectOverlayCharacters()
    {
        var set = new System.Collections.Generic.HashSet<char>();
        for (int lang = 0; lang < Data.Length; lang++)
        {
            var arr = Data[lang];
            for (int i = 0; i < arr.Length; i++)
            {
                var s = arr[i];
                for (int j = 0; j < s.Length; j++) set.Add(s[j]);
            }
        }
        return string.Concat(set);
    }
}
